import {
  CakeCategory,
  CakeFlavor,
  Frosting,
  CakeSize,
  Decoration,
  Profile,
  CakeDesign,
  Order,
  NotificationItem,
} from '../types/database.types';

export const MOCK_CATEGORIES: CakeCategory[] = [
  {
    id: 'cat-birthday',
    name: 'Birthday',
    slug: 'birthday',
    description: 'Celebrate milestones with vibrant, joyous handcrafted cake designs.',
    image_url: 'https://images.unsplash.com/photo-1558301211-0d8c8ddee6ec?w=600&auto=format&fit=crop&q=80',
    base_price: 799,
    active: true,
  },
  {
    id: 'cat-wedding',
    name: 'Wedding',
    slug: 'wedding',
    description: 'Sophisticated multi-tier architectural masterpieces for your special day.',
    image_url: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=600&auto=format&fit=crop&q=80',
    base_price: 2499,
    active: true,
  },
  {
    id: 'cat-anniversary',
    name: 'Anniversary',
    slug: 'anniversary',
    description: 'Romantic heart shapes, subtle pastels and edible floral decorations.',
    image_url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',
    base_price: 999,
    active: true,
  },
  {
    id: 'cat-kids',
    name: 'Kids & Cartoon',
    slug: 'kids',
    description: 'Fun, colorful 3D themed character cakes that bring magical stories to life.',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    base_price: 899,
    active: true,
  },
  {
    id: 'cat-baby-shower',
    name: 'Baby Shower',
    slug: 'baby-shower',
    description: 'Gentle pastels, sweet cloud motifs, and delicate keepsake toppers.',
    image_url: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=600&auto=format&fit=crop&q=80',
    base_price: 949,
    active: true,
  },
  {
    id: 'cat-graduation',
    name: 'Graduation',
    slug: 'graduation',
    description: 'Academic caps, diplomas, and customized celebratory gold accents.',
    image_url: 'https://images.unsplash.com/photo-1532499016263-f2c3e89de9cd?w=600&auto=format&fit=crop&q=80',
    base_price: 899,
    active: true,
  },
  {
    id: 'cat-celebration',
    name: 'Celebration',
    slug: 'celebration',
    description: 'Luxurious modern cakes for corporate events, parties, and triumphs.',
    image_url: 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?w=600&auto=format&fit=crop&q=80',
    base_price: 1099,
    active: true,
  },
  {
    id: 'cat-custom',
    name: 'Custom AI Creation',
    slug: 'custom',
    description: 'Pure creative freedom powered by the Dream Cake AI generative studio.',
    image_url: 'https://images.unsplash.com/photo-1535254973040-607b474cb50d?w=600&auto=format&fit=crop&q=80',
    base_price: 899,
    active: true,
  },
];

export const MOCK_FLAVORS: CakeFlavor[] = [
  {
    id: 'flv-chocolate',
    name: 'Belgian Chocolate Truffle',
    description: 'Rich dark chocolate sponge layered with smooth 54% Callebaut truffle ganache.',
    image_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=300&auto=format&fit=crop&q=80',
    price_modifier: 150,
    active: true,
  },
  {
    id: 'flv-vanilla',
    name: 'Madagascar Vanilla Bean',
    description: 'Light, fluffy sponge infused with aromatic organic vanilla bean caviar.',
    image_url: 'https://images.unsplash.com/photo-1542826438-bd32f43d626f?w=300&auto=format&fit=crop&q=80',
    price_modifier: 50,
    active: true,
  },
  {
    id: 'flv-red-velvet',
    name: 'Royal Red Velvet',
    description: 'Velvety crimson cocoa crumb paired with our signature light cream cheese pairing.',
    image_url: 'https://images.unsplash.com/photo-1586788680434-30d324b2d46f?w=300&auto=format&fit=crop&q=80',
    price_modifier: 180,
    active: true,
  },
  {
    id: 'flv-butterscotch',
    name: 'Crunchy Butterscotch',
    description: 'Caramelized praline crunch folded into golden brown sugar butter sponge.',
    image_url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=300&auto=format&fit=crop&q=80',
    price_modifier: 120,
    active: true,
  },
  {
    id: 'flv-black-forest',
    name: 'Classic Black Forest',
    description: 'Kirsch-soaked chocolate sponge with tart sour cherries and whipped Chantilly.',
    image_url: 'https://images.unsplash.com/photo-1606890737304-57a1ca8a5b62?w=300&auto=format&fit=crop&q=80',
    price_modifier: 140,
    active: true,
  },
  {
    id: 'flv-white-forest',
    name: 'White Forest Blossom',
    description: 'White chocolate shavings with wild berry compote and delicate vanilla cream.',
    image_url: 'https://images.unsplash.com/photo-1562440499-64c9a111f713?w=300&auto=format&fit=crop&q=80',
    price_modifier: 130,
    active: true,
  },
  {
    id: 'flv-strawberry',
    name: 'Fresh Strawberry Rose',
    description: 'Sun-ripened strawberry puree with a whisper of organic Damask rosewater.',
    image_url: 'https://images.unsplash.com/photo-1464349095431-e9a21285b5f3?w=300&auto=format&fit=crop&q=80',
    price_modifier: 160,
    active: true,
  },
  {
    id: 'flv-mango',
    name: 'Tropical Alphonso Mango',
    description: 'Pure Ratnagiri Alphonso mango mousse between tender coconut sponge.',
    image_url: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=300&auto=format&fit=crop&q=80',
    price_modifier: 200,
    active: true,
  },
  {
    id: 'flv-pistachio',
    name: 'Persian Pistachio Saffron',
    description: 'Finely ground green pistachios infused with Kashmiri saffron strands.',
    image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=300&auto=format&fit=crop&q=80',
    price_modifier: 250,
    active: true,
  },
  {
    id: 'flv-caramel',
    name: 'Salted Caramel Espresso',
    description: 'Dark espresso soak balanced with sea-salted artisan dairy caramel.',
    image_url: 'https://images.unsplash.com/photo-1550617931-e17a7b70dce2?w=300&auto=format&fit=crop&q=80',
    price_modifier: 170,
    active: true,
  },
];

export const MOCK_FROSTINGS: Frosting[] = [
  {
    id: 'frst-buttercream',
    name: 'Swiss Meringue Buttercream',
    description: 'Silky, velvety, and balanced in sweetness with high stability for piped designs.',
    price_modifier: 80,
    active: true,
  },
  {
    id: 'frst-whipped',
    name: 'Whipped Chantilly Cream',
    description: 'Ultra-light, airy, and refreshing cream with subtle vanilla notes.',
    price_modifier: 0,
    active: true,
  },
  {
    id: 'frst-ganache',
    name: 'Chocolate Ganache Gloss',
    description: 'Decadent, rich melted dark chocolate glaze with a mirror finish.',
    price_modifier: 140,
    active: true,
  },
  {
    id: 'frst-cream-cheese',
    name: 'Tangy Cream Cheese',
    description: 'Smooth, mildly tart premium Philadelphia style cream cheese.',
    price_modifier: 120,
    active: true,
  },
  {
    id: 'frst-fondant',
    name: 'Artisan Sugar Fondant',
    description: 'Flawless porcelain smooth surface ideal for intricate sculpting and painting.',
    price_modifier: 220,
    active: true,
  },
];

export const MOCK_SIZES: CakeSize[] = [
  {
    id: 'sz-0.5',
    name: '0.5 kg (Bento / Petite)',
    weight_kg: 0.5,
    servings: '2 - 4 servings',
    price_modifier: 0,
    active: true,
  },
  {
    id: 'sz-1.0',
    name: '1.0 kg (Classic Small)',
    weight_kg: 1.0,
    servings: '6 - 8 servings',
    price_modifier: 350,
    active: true,
  },
  {
    id: 'sz-1.5',
    name: '1.5 kg (Party Medium)',
    weight_kg: 1.5,
    servings: '10 - 12 servings',
    price_modifier: 650,
    active: true,
  },
  {
    id: 'sz-2.0',
    name: '2.0 kg (Celebration Large)',
    weight_kg: 2.0,
    servings: '14 - 18 servings',
    price_modifier: 950,
    active: true,
  },
  {
    id: 'sz-3.0',
    name: '3.0 kg (Grand Multi-tier)',
    weight_kg: 3.0,
    servings: '22 - 28 servings',
    price_modifier: 1550,
    active: true,
  },
  {
    id: 'sz-4.0',
    name: '4.0 kg (Royal Banquet)',
    weight_kg: 4.0,
    servings: '30 - 38 servings',
    price_modifier: 2150,
    active: true,
  },
  {
    id: 'sz-5.0',
    name: '5.0 kg+ (Gala Showpiece)',
    weight_kg: 5.0,
    servings: '40 - 55 servings',
    price_modifier: 2850,
    active: true,
  },
];

export const MOCK_DECORATIONS: Decoration[] = [
  {
    id: 'dec-roses',
    name: 'Handcrafted Edible Sugar Roses',
    category: 'Flowers',
    description: 'Artisan hand-piped sugar petal roses with gold tipped edges.',
    image_url: '🌸',
    price_modifier: 220,
    active: true,
  },
  {
    id: 'dec-berries',
    name: 'Fresh Organic Berries & Figs',
    category: 'Fruits',
    description: 'Fresh raspberries, blueberries, blackberries and cut mission figs.',
    image_url: '🍓',
    price_modifier: 180,
    active: true,
  },
  {
    id: 'dec-gold',
    name: '24K Edible Gold Leaf Accents',
    category: 'Gold Accents',
    description: 'Gleaming genuine 24-karat gold leaf flakes applied by hand.',
    image_url: '✨',
    price_modifier: 250,
    active: true,
  },
  {
    id: 'dec-drip',
    name: 'Artisan Chocolate Drip & Shards',
    category: 'Chocolates',
    description: 'Rich dark chocolate dripping cascades with hand-tempered geometric shards.',
    image_url: '🍫',
    price_modifier: 140,
    active: true,
  },
  {
    id: 'dec-topper',
    name: 'Acrylic Laser Cut Name Topper',
    category: 'Toppers',
    description: 'Custom laser cut golden acrylic calligraphy cake topper.',
    image_url: '🎂',
    price_modifier: 160,
    active: true,
  },
  {
    id: 'dec-piping',
    name: 'Vintage Royal Lambeth Piping',
    category: 'Piping',
    description: 'Intricate Victorian ruffles and vintage scroll borders.',
    image_url: '🎀',
    price_modifier: 190,
    active: true,
  },
  {
    id: 'dec-print',
    name: 'Edible High-Res Photo Print',
    category: 'Edible Prints',
    description: 'Crystal clear edible icing sheet printing with food-grade colors.',
    image_url: '🖼️',
    price_modifier: 150,
    active: true,
  },
  {
    id: 'dec-pearls',
    name: 'Sparkling Pearl & Gold Sprinkles',
    category: 'Sprinkles',
    description: 'Crisp chocolate-centered metallic pearls in various sizes.',
    image_url: '⭐',
    price_modifier: 80,
    active: true,
  },
  {
    id: 'dec-character',
    name: '3D Custom Figurines',
    category: 'Figures',
    description: 'Detailed miniature sculpted fondant character based on your theme.',
    image_url: '🧸',
    price_modifier: 350,
    active: true,
  },
];

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'usr-customer-1',
    auth_user_id: 'auth-customer-1',
    full_name: 'Ananya Sharma',
    email: 'customer@dreamcake.ai',
    phone: '+91 98765 43210',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
    role: 'customer',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr-staff-1',
    auth_user_id: 'auth-staff-1',
    full_name: 'Chef Marco Rossi (Head Baker)',
    email: 'staff@dreamcake.ai',
    phone: '+91 98765 12345',
    avatar_url: 'https://images.unsplash.com/photo-1583394293214-28ded15ee548?w=150&auto=format&fit=crop&q=80',
    role: 'staff',
    created_at: new Date(Date.now() - 60 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'usr-admin-1',
    auth_user_id: 'auth-admin-1',
    full_name: 'Priya Iyer (Bakery Owner)',
    email: 'admin@dreamcake.ai',
    phone: '+91 98765 99999',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'admin',
    created_at: new Date(Date.now() - 90 * 86400000).toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const INITIAL_DESIGNS: CakeDesign[] = [
  {
    id: 'dsg-1',
    user_id: 'usr-customer-1',
    name: 'Rose Romance Tiered Elegance',
    occasion: 'Anniversary',
    category_id: 'cat-anniversary',
    flavor_id: 'flv-red-velvet',
    frosting_id: 'frst-cream-cheese',
    size_id: 'sz-1.5',
    shape: 'Heart',
    tiers: 2,
    theme: 'Floral Luxury',
    primary_color: '#FFF1F4',
    secondary_color: '#BE123C',
    accent_color: '#D4AF37',
    decorations: ['Handcrafted Edible Sugar Roses', '24K Edible Gold Leaf Accents'],
    cake_message: 'Forever & Always ❤️',
    special_requirements: 'Less sweet, extra rose water note in cream.',
    reference_image_url: 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=600&auto=format&fit=crop&q=80',
    ai_preview_url: 'https://images.unsplash.com/photo-1535141192574-5d4897c13136?w=600&auto=format&fit=crop&q=80',
    ai_analysis: {
      theme: 'Luxury Floral Romance',
      detectedShape: 'Heart',
      estimatedTiers: 2,
      complexityScore: 'Intricate',
      detectedColors: {
        primary: '#FFF1F4',
        secondary: '#BE123C',
        accent: '#D4AF37',
        paletteName: 'Rose & Champagne Gold',
      },
    },
    estimated_price: 2150,
    status: 'READY',
    is_favorite: true,
    created_at: new Date(Date.now() - 5 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
  {
    id: 'dsg-2',
    user_id: 'usr-customer-1',
    name: 'Golden Truffle 30th Milestone',
    occasion: 'Birthday',
    category_id: 'cat-birthday',
    flavor_id: 'flv-chocolate',
    frosting_id: 'frst-ganache',
    size_id: 'sz-2.0',
    shape: 'Round',
    tiers: 1,
    theme: 'Modern Luxury',
    primary_color: '#26150D',
    secondary_color: '#D4AF37',
    accent_color: '#E5C039',
    decorations: ['Artisan Chocolate Drip & Shards', '24K Edible Gold Leaf Accents', 'Acrylic Laser Cut Name Topper'],
    cake_message: 'Happy 30th Siddharth!',
    special_requirements: 'Dark chocolate 70% if available.',
    reference_image_url: '',
    ai_preview_url: 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=600&auto=format&fit=crop&q=80',
    estimated_price: 2450,
    status: 'READY',
    is_favorite: false,
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-101',
    order_number: 'DC-89421',
    user_id: 'usr-customer-1',
    design_id: 'dsg-1',
    assigned_staff_id: 'usr-staff-1',
    order_type: 'DELIVERY',
    requested_date: new Date(Date.now() + 3 * 86400000).toISOString().split('T')[0],
    requested_time: '5:00 PM - 7:00 PM',
    customer_notes: 'Please ring bell and leave with front desk if not answering.',
    estimated_price: 2150,
    final_price: 2300,
    customer_confirmed_price: true,
    payment_status: 'PAID',
    order_status: 'PREPARING',
    created_at: new Date(Date.now() - 2 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 3600000).toISOString(),
    design: INITIAL_DESIGNS[0],
    customer: DEMO_PROFILES[0],
    assigned_staff: DEMO_PROFILES[1],
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    user_id: 'usr-customer-1',
    title: 'Order Status Update',
    message: 'Chef Marco Rossi has started preparing your "Rose Romance Tiered Elegance" cake!',
    type: 'ORDER_STATUS',
    order_id: 'ord-101',
    read: false,
    created_at: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'notif-2',
    user_id: 'usr-customer-1',
    title: 'Price Confirmed & Locked',
    message: 'Your bakery confirmed the quote of ₹2,300. Preparation is scheduled on time.',
    type: 'PRICE_UPDATE',
    order_id: 'ord-101',
    read: true,
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];
